### ISSUE TITLE
[Roadmap] Application wrapper

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher-NEXT#2]
It needs to be decided which application wrapper to use.

The only 2 that I know of are:

- [Electron](http://electron.atom.io/)
- [NW.js](http://nwjs.io/)

**Comment by jamierocks** [comment]
My preferences lie with Electron.

**Comment by RyanTheAllmighty** [comment]
I also prefer Electron but have come across transition delays on SPA's in the past with Electron only which I need to investigate if they still occur.

**Comment by RyanTheAllmighty** [comment]
I think Electron will be the way to go.

For the reason I stated above as well as [this](https://github.com/sindresorhus/awesome-electron) list of awesome stuff for Electron and not being able to reproduce the transition bug it seems to be the best choice for a constantly updated application.

**Comment by RyanTheAllmighty** [comment]
One downside with Electron is it only supports Windows 7 and above and OSX 10.9 and above whereas NW.js supports XP and above and OSX 10.6 and above.

**Comment by jamierocks** [comment]
Well let's be real if you're running XP, chances are you ain't going to be running many packs anyway.

**Comment by RyanTheAllmighty** [comment]
Alright so looking through the launcher statistics:

**Windows Versions**
- 5.1 (XP) = 48,203
- 5.2 (XP). = 380
- 6.0 (Vista) = 77,243
- XP and Vista Users = 125,826
- Windows Users = 17,335,651

That's roughly 0.725% of all users using XP or Vista and would be cut off if using Electron.

**OSX Versions**
- 10.5 or below = 2,254
- 10.7 or below = 69,977
- OSX Users = 1,433,923

That's roughly 4.88% of all users using OSX 10.6 or 10.7 and would be cut off if using Electron.IF using NW.js we'd be cutting off 0.157% of users.

**Comment by RyanTheAllmighty** [comment]
So in summary using Electron would cut off roughly 5.605% of our current userbase, whereas NW.js would cut off only 0.157% of our current userbase.

**Comment by jamierocks** [comment]
IMO they are legacy systems, and it'd be a shame if ATL wasn't using the best framework to support legacy systems.

**Comment by RyanTheAllmighty** [comment]
Well based on this current weeks stats, we've had **72,342** unique users using the platform, which if we did use electron, it would roughly cut off **3,612** users which is a massive number compared to a loss of approximately **113** if using NW.js.

Now of course this is just an approximation, but something to be wary of.

**Comment by RyanTheAllmighty** [comment]
So relooking at this with new statistics I can see that **0.78%** of windows users would be cut off if using Electron and **43.36%** of OSX users would be cut off.

OSX accounts for roughly **7.89%** of all launches.

I still don't feel comfortable cutting off a large possible chunk of users even given Electron's superior framework.

**Comment by Isigiel** [comment]
Also take into account how future prrof both solutions are ...

**Comment by Cherry** [comment]
Discussed this with Ryan privately, but adding to the discussion here for visibility.

Windows XP support was dropped by Microsoft, both in terms of features and security updates on __April 8, 2014__. Whilst there may still be some people using such an outdated OS, I think these users can be safely ignored. Windows Vista support is scheduled to be cut on __April 11, 2017__, which is a little more concerning.

Regarding OSX, Apple don't officially publish "end of life" dates for support/security updates of their software as far as I'm aware, but the latest 10.5 build was released in __2009__, and the latest 10.7 in __2012__. 10.7 is the only concern here, in my opinion.

NW.js is currently on version 0.15.4 stable, and working towards 0.16 beta. Both of these versions no longer support Windows XP or older OS X builds, due to support being dropped in Chromium, but they do maintain an _LTS_ branch, albeit slightly dated now, at their 0.14 version; http://nwjs.io/downloads/

Electron doesn't support Windows XP whatsoever, and requires Windows 7+. It officially also requires macOS 10.9.

To conclude, my vote is 100% for Electron. It would alienate some users, but is by far the better platform.

**Comment by RyanTheAllmighty** [comment]
Surprisingly OSX 10.5 makes up a majority of all OSX users.

Now I think 10.5 works with Electron, it's just not officially supported.

**Comment by RyanTheAllmighty** [comment]
And yes I agree that Electron should be used. Will do more research and come to a decision by end of this weekend, but I think it's going to be Electron.

**Comment by RyanTheAllmighty** [comment]
Alright Electron is going to be our application wrapper.

**Comment by jamierocks** [comment]
Awesome
